name: 'Execução Manual teste'

on:
  workflow_dispatch:

jobs:
  rodar-trabalho-final:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout do repositório principal (onde este workflow está)
      - name: Checkout do repositório principal
        uses: actions/checkout@v4

      # 2) Checkout do repositório que contém os testes
      - name: Checkout do repositório de testes
        uses: actions/checkout@v4
        with:
          repository: angelapaulam/minha-pgats-aprogramacao-js
          path: minha-pgats-aprogramacao-js
          
      # 3) Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # 4) Instalar dependências (caso precise)
      - name: Instalando dependências do projeto de testes
        run: |
          yarn
        working-directory: minha-pgats-aprogramacao-js/testes

      # 5) Instalar navegadores do Playwright
      - name: Instalando Playwright
        run: npx playwright install
        working-directory: minha-pgats-aprogramacao-js/testes

      # 6) Executar o script trabalho-final.js
      - name: Executar trabalho-final.js
        run: node trabalho-final.js
        working-directory: minha-pgats-aprogramacao-js/testes
