name: 'Execução Manual Trabalho Final'

on:
  workflow_dispatch:

jobs:
  rodar-trabalho-final:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout do repositório principal (pgats-ci-lab-meu)
      - name: Checkout principal
        uses: actions/checkout@v4

      # 2) Checkout do repositório que contém os testes
      - name: Checkout do repo de testes
        uses: actions/checkout@v4
        with:
          repository: angelapaulam/minha-pgats-aprogramacao-js
          path: minha-pgats-aprogramacao-js

      # 3) Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      # 4) Executar o script trabalho-final.js
      - name: Executar trabalho-final.js
        run: node minha-pgats-aprogramacao-js/testes/trabalho-final.js
