name: Executar Teste Trabalho Final

on:
  workflow_dispatch:

jobs:
  playwright-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Instalando dependências
        run: npm install
        working-directory: pgats-aprogramacao-js

      - name: Instalando navegadores do Playwright
        run: npx playwright install
        working-directory: pgats-aprogramacao-js

      - name: Executando teste específico da pasta 'testes'
        run: npx playwright test testes
        working-directory: pgats-aprogramacao-js
