name: 'Execução Manual Trabalho Final'

on:
  workflow_dispatch:

jobs:
  rodar-trabalho-final:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Executar trabalho-final.js
        run: node ../minha-pgats-aprogramacao-js/testes/trabalho-final.js
        working-directory: ./posautomacao
