name: 'Execução Manual trabalho final'

on:
  workflow_dispatch:

jobs:
  rodar-trabalho-final:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout do repositório principal
      - name: Checkout principal
        uses: actions/checkout@v4

      # 2) Checkout do repositório que contém os testes
      - name: Checkout do repositório de testes
        uses: actions/checkout@v4
        with:
          repository: angelapaulam/minha-pgats-aprogramacao-js
          path: minha-pgats-aprogramacao-js

      # 3) Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      # 4) Instalar dependências e navegadores Playwright na pasta de testes
      - name: Instalando dependências e Playwright
        run: |
          cd minha-pgats-aprogramacao-js/testes
          yarn
          npx playwright install

      # 5) Executar o script trabalho-final.js
      - name: Executar trabalho-final.js
        run: |
          cd minha-pgats-aprogramacao-js/testes
          node trabalho-final.js
