name: 'Execução Manual Trabalho-Final'

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Entrando na pasta do projeto
        run: ../minha-pgats-aprogramacao-js/testes/trabalho-final.js

      - name: Instalando dependências
        run: 
          cd ../minha-pgats-aprogramacao-js/testes/trabalho-final.js
          yarn

      - name: Instalando Playwright
        run: 
          cd ../minha-pgats-aprogramacao-js/testes/trabalho-final.js
          yarn playwright install

      - name: Executando Testes E2E
        run: 
          cd ../minha-pgats-aprogramacao-js/testes/trabalho-final.js
          yarn run e2e
