name: 'Execução Manual Trabalho Final'

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout do repositório
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # Instala dependências
      - name: Instalar dependências (com --legacy-peer-deps para evitar conflitos)
        run: npm install --legacy-peer-deps

      # Instala Playwright
      - name: Instalar Playwright
        run: npx playwright install

      # Executa o teste final
      - name: Executar testes do trabalho final
        run: npm run test:final