name: 'Execução Manual Trabalho-Final'

on:
  workflow_dispatch:

jobs:
  rodar-trabalho-final:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Instalar dependências (caso tenha package.json)
        run: |
          if [ -f "package.json" ]; then
            yarn install || npm install
          else
            echo "Nenhum package.json encontrado, pulando instalação de dependências."
          fi

      - name: Verificar estrutura de pastas
        run: ls -R

      - name: Executar trabalho-final.js
        run: node testes/trabalho-final.js