name: Rodar Testes de Outro Repositório

on:
  workflow_dispatch:

jobs:
  executar-testes:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório atual (pgats-ci-lab-meu)
      - name: Checkout do repositório principal
        uses: actions/checkout@v4

      # Checkout do repositório com os testes (minha-pgats-aprogramacao-js)
      - name: Checkout do repositório de testes
        uses: actions/checkout@v4
        with:
          repository: usuario/minha-pgats-aprogramacao-js
          path: minha-pgats-aprogramacao-js
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Instalando dependências
        run: npm install
        working-directory: minha-pgats-aprogramacao-js/testes

      - name: Instalando navegadores do Playwright
        run: npx playwright install
        working-directory: minha-pgats-aprogramacao-js/testes

      - name: Rodando os testes
        run: npx playwright test
        working-directory: minha-pgats-aprogramacao-js/testes
