name: 'Execução Manual Trabalho-Final'

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          repository: posautomacao/minha-pgats-aprogramacao-js
          path: minha-pgats-aprogramacao-js
          
      - name: Instalando dependências
        run: npm install
        working-directory: minha-pgats-aprogramacao-js/testes

      - name: Instalando navegadores do Playwright
        run: npx playwright install
        working-directory: minha-pgats-aprogramacao-js/testes

      - name: Rodando os testes
        run: npx playwright test
        working-directory: minha-pgats-aprogramacao-js/testes
