name: 'Execução Manual Trabalho Final'

on:
  workflow_dispatch:

jobs:
  rodar-trabalho-final:
    runs-on: ubuntu-latest

    steps:
      # 1) Faz checkout de TODO o repositório posautomacao
      - uses: actions/checkout@v4

      # 2) Prepara o Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      # 3) Executa o script trabalho-final.js a partir da raiz
      - name: Executar trabalho-final.js
        run: node minha-pgats-aprogramacao-js/testes/trabalho-final.js
