name: 'Execução Manual Trabalho Final'

on:
  workflow_dispatch:

jobs:
  rodar-trabalho-final:
    runs-on: ubuntu-latest

    steps:
      # 1) Faz checkout de TODO o repositório (inclui ambas as pastas)
      - uses: actions/checkout@v4

      # 2) Prepara o Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      # 3) Instala as dependências onde está o package.json
      - name: Instalando dependências
        run: npm install
        working-directory: minha-pgats-aprogramacao-js

      # 4) Executa o script trabalho-final.js
      - name: Executar trabalho-final.js
        run: node testes/trabalho-final.js
        working-directory: minha-pgats-aprogramacao-js