name: 'Execução Manual Trabalho Final'

on:
  workflow_dispatch:

jobs:
  executar-trabalho-final:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Criar setup.js vazio para Jest (workaround)
        run: |
          mkdir -p test
          echo "" > test/setup.js

      - name: Instalando dependências
        run: npm install --legacy-peer-deps

      - name: Rodando trabalho-final.js com Jest
        run: npm test -- testes/trabalho-final.js