name: 'Execução Manual Trabalho-Final'

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Instalando Yarn
        run: npm install -g yarn
        
      - name: Instalando dependências
        run: yarn
        working-directory: pgats-ci-lab-trabalho-final

      - name: Instalando Playwright
        run: yarn playwright install
        working-directory: pgats-ci-lab-trabalho-final

      - name: Executando Testes E2E
        run: yarn run e2e
        working-directory: pgats-ci-lab-trabalho-final
